name: Lint and test code
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install shellcheck
      #   run: sudo apt-get update && apt-get install shellcheck
      - name: Lint
        run: make lint
  e2e-test:
    name: E2E test
    runs-on: ubuntu-latest
    needs: [lint]
    strategy: 
      matrix:
        k8s_version: [v1.16.0, v1.17.0, v1.18.0, v1.19.0]
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      # - name: Install minikube
      #   run: |
      #     curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      #     dpkg -i minikube_latest_amd64.deb
      - name: test
        run: ./e2e-tests/tests.sh
        env:
            E2E_KUBERNETES_VERSION: ${{ matrix.k8s_version }}
            E2E_SETUP_MINIKUBE: true
            E2E_SETUP_KUBECTL: true
            E2E_START_MINIKUBE: true

